### ISSUE TITLE
style: run ruff checks on ci

### ISSUE THREAD

**Issue by kszucs** [kszucs/koerce#14]

**Comment by IndexSeek** [comment]
Hey @kszucs! I'd be interested in helping with this one. 

I did a preliminary `ruff check`, and I'm getting the following totals (some of these are coming from the tests, too):

| Rule    | Count |
|----------|-----------------|
| [BLE001](https://docs.astral.sh/ruff/rules/blind-except/)  | 4               |
| [D417](https://docs.astral.sh/ruff/rules/undocumented-param/)     | 2               |
| [E402](https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/)     | 4               |
| [F401](https://docs.astral.sh/ruff/rules/unused-import/)     | 1               |
| [F403](https://docs.astral.sh/ruff/rules/undefined-local-with-import-star/)     | 4               |
| [F405](https://docs.astral.sh/ruff/rules/undefined-local-with-import-star-usage/)     | 12              |
| [F811](https://docs.astral.sh/ruff/rules/redefined-while-unused/)     | 4               |
| [F821](https://docs.astral.sh/ruff/rules/undefined-name/)    | 1               |
| [PLR1714](https://docs.astral.sh/ruff/rules/repeated-equality-comparison/)  | 2               |
| [RUF012](https://docs.astral.sh/ruff/rules/mutable-class-default/)   | 3               |
| [RUF100](https://docs.astral.sh/ruff/rules/unused-noqa/)   | 1               |
| [SIM110](https://docs.astral.sh/ruff/rules/reimplemented-builtin/)   | 2               |

<details closed>
<summary>Verbose Output</summary>
  
koerce/__init__.py:5:1: F403 `from ._internal import *` used; unable to detect undefined names
koerce/__init__.py:8:17: F405 `Deferred` may be undefined, or defined from star imports
koerce/__init__.py:10:19: F405 `Var` may be undefined, or defined from star imports
koerce/__init__.py:14:16: F405 `Capture` may be undefined, or defined from star imports
koerce/__init__.py:53:20: F405 `pattern` may be undefined, or defined from star imports
koerce/__init__.py:54:20: F405 `deferred` may be undefined, or defined from star imports
koerce/__init__.py:62:16: F405 `Replace` may be undefined, or defined from star imports
koerce/__init__.py:74:5: D417 Missing argument description in the docstring for `koerce`: `allow_coercion`
koerce/__init__.py:75:10: F405 `Pattern` may be undefined, or defined from star imports
koerce/__init__.py:75:26: F405 `Any` may be undefined, or defined from star imports
koerce/__init__.py:75:40: F405 `Context` may be undefined, or defined from star imports
koerce/__init__.py:76:6: F405 `Any` may be undefined, or defined from star imports
koerce/__init__.py:107:11: F405 `pattern` may be undefined, or defined from star imports
koerce/__init__.py:110:12: F405 `MatchError` may be undefined, or defined from star imports
koerce/_internal.py:3:1: F403 `from .annots import *` used; unable to detect undefined names
koerce/_internal.py:4:1: F403 `from .builders import *` used; unable to detect undefined names
koerce/_internal.py:5:1: F403 `from .patterns import *` used; unable to detect undefined names
koerce/annots.py:743:19: RUF100 Unused `noqa` directive (unused: `SIM105`)
koerce/annots.py:841:33: F821 Undefined name `Self`
koerce/patterns.py:806:16: PLR1714 Consider merging multiple comparisons: `lowered in ("true", "1")`. Use a `set` if the elements are hashable.
koerce/patterns.py:808:18: PLR1714 Consider merging multiple comparisons: `lowered in ("false", "0")`. Use a `set` if the elements are hashable.
koerce/patterns.py:904:16: BLE001 Do not catch blind exception: `Exception`
koerce/patterns.py:936:16: BLE001 Do not catch blind exception: `Exception`
koerce/patterns.py:977:16: BLE001 Do not catch blind exception: `Exception`
koerce/patterns.py:1027:16: BLE001 Do not catch blind exception: `Exception`
koerce/patterns.py:2558:5: D417 Missing argument descriptions in the docstring for `pattern`: `allow_coercion`, `self_qualname`
koerce/tests/test_annots.py:705:9: F811 Redefinition of unused `test` from line 701
koerce/tests/test_annots.py:722:9: F811 Redefinition of unused `test` from line 718
koerce/tests/test_annots.py:999:9: SIM110 Use `return all(a == b for a, b in zip(self, other))` instead of `for` loop
koerce/tests/test_annots.py:1051:9: SIM110 Use `return all(self[key] == other[key] for key in self)` instead of `for` loop
koerce/tests/test_annots.py:1244:11: F811 Redefinition of unused `Op2` from line 1241
koerce/tests/test_annots.py:2183:31: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
koerce/tests/test_builders.py:209:5: F811 Redefinition of unused `resolve` from line 28
koerce/tests/test_y.py:13:1: E402 Module level import not at top of file
koerce/tests/test_y.py:14:1: E402 Module level import not at top of file
koerce/tests/test_y.py:15:1: E402 Module level import not at top of file
koerce/tests/test_y.py:17:1: E402 Module level import not at top of file
koerce/tests/test_y.py:171:27: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
koerce/tests/test_y.py:178:27: RUF012 Mutable class attributes should be annotated with `typing.ClassVar`
koerce/utils.py:7:25: F401 `typing.ClassVar` imported but unused
</details>

Would you like to add any of these rules to the ruff ignore list, or should we mark them as #noqa?

**Comment by kszucs** [comment]
We should also add a build running the ruff checks.
